name: release

on:
    release:
        types: [created]

jobs:
    release-linux-amd64:
        name: release linux/amd64
        runs-on: ubuntu-latest
        strategy:
            matrix:
                goos: [linux, windows]
                goarch: [amd64]
        steps:
            - uses: actions/checkout@v2
            - uses: wangyoucao577/go-release-action@v1.25
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  goos: ${{ matrix.goos }}
                  goarch: ${{ matrix.goarch }}
                  goversion: https://go.dev/dl/go1.18rc1.linux-amd64.tar.gz
                  extra_files: LICENSE README.md lua
